// This file is auto-generated by @hey-api/openapi-ts

export const $Actor = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $Movie = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string',
            nullable: true
        },
        year: {
            type: 'integer',
            format: 'int32'
        },
        summary: {
            type: 'string',
            nullable: true
        },
        director: {
            type: 'string',
            nullable: true
        },
        genres: {
            type: 'array',
            items: {
                type: 'string'
            },
            nullable: true
        },
        actors: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Actor'
            },
            nullable: true
        },
        posterPath: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;