// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiMoviesResponse, PostApiMoviesData, PostApiMoviesResponse, GetApiMoviesByIdData, GetApiMoviesByIdResponse, PutApiMoviesByIdData, PutApiMoviesByIdResponse, DeleteApiMoviesByIdData, DeleteApiMoviesByIdResponse } from './types.gen';

/**
 * @returns Movie Success
 * @throws ApiError
 */
export const getApiMovies = (): CancelablePromise<GetApiMoviesResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/movies'
}); };

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns void No Content
 * @throws ApiError
 */
export const postApiMovies = (data: PostApiMoviesData): CancelablePromise<PostApiMoviesResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/movies',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @param data The data for the request.
 * @param data.id
 * @returns Movie Success
 * @throws ApiError
 */
export const getApiMoviesById = (data: GetApiMoviesByIdData): CancelablePromise<GetApiMoviesByIdResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/movies/{id}',
    path: {
        id: data.id
    }
}); };

/**
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns Movie Success
 * @throws ApiError
 */
export const putApiMoviesById = (data: PutApiMoviesByIdData): CancelablePromise<PutApiMoviesByIdResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/movies/{id}',
    path: {
        id: data.id
    },
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @param data The data for the request.
 * @param data.id
 * @returns void No Content
 * @throws ApiError
 */
export const deleteApiMoviesById = (data: DeleteApiMoviesByIdData): CancelablePromise<DeleteApiMoviesByIdResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/movies/{id}',
    path: {
        id: data.id
    }
}); };